comment_width = 120
edition  = "2021"
format_code_in_doc_comments = true
max_width = 120
imports_granularity = "Crate"
normalize_comments = true
normalize_doc_attributes = true
use_field_init_shorthand = true
wrap_comments = true
