name: Test

on:
  pull_request:
  push:
    branches:
      - 'develop'
      - 'main'

jobs:
  idk:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: actions-rs/cargo@v1
        timeout-minutes: 15
        with:
          command: tests
          args: --release --all-features
